spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/drive-tuning-portal-db?autoReconnect=true&useSSL=false
    username: root
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  queries:
    users-query: select email, password, email_verified from users where email=?
    roles-query: select u.email, r.role from users u inner join user_role ur on u.user_id=ur.user_id inner join roles r on(ur.role_id=r.role_id) where u.email=?